name: Terraform

on:
  push:
    branches:
      - main

  workflow_dispatch:

jobs:
  terraform:
    runs-on: ubuntu-latest

    defaults:
      run:
        working-directory: terraform

    env:
      TF_VAR_nebius_token: ${{ secrets.NEBIUS_TOKEN }}
      TF_VAR_project_id: ${{ secrets.PROJECT_ID }}

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3

      - name: Terraform Init
        run: terraform init

      - name: Terraform Validate
        run: terraform validate

      - name: Debug Environment
        run: |
          echo "PROJECT_ID present? $([ -n "$TF_VAR_project_id" ] && echo YES || echo NO)"
          echo "TOKEN present? $([ -n "$TF_VAR_nebius_token" ] && echo YES || echo NO)"

      - name: Terraform Plan
        run: terraform plan -input=false

      - name: Terraform Apply
        if: github.event_name == 'workflow_dispatch'
        run: terraform apply -auto-approve -input=false